/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  static const String PLUGIN_NAME = 'flutterprojectanimations';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String ORTENSIALILY_CREEPY_SONG_276076 = 'assets/audio/ortensialily-creepy-song-276076.mp3';
  static const String CD = 'assets/images/cd.png';
}
